@TaskForMoodivationStack.WebApi_HostAddress = http://localhost:5128

POST {{TaskForMoodivationStack.WebApi_HostAddress}}/api/Customers/Register
Accept: application/json
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "striasdsng",
  "email": "string@stsadring.com",
  "password": "string1234"
}

###

POST {{TaskForMoodivationStack.WebApi_HostAddress}}/api/Orders/Add
Accept: application/json
Content-Type: application/json

{
  "customerId": "fdebb987-6188-48e6-ad13-a34c32451f5f",
  "priceCurrency": "TRY",
  "priceAmount": 30
}

###


GET {{TaskForMoodivationStack.WebApi_HostAddress}}/api/Orders/a45eb317-1aa5-4922-ba59-9414142d9827
Accept: application/json
###


//https://localhost:7122/api/Customers/RegisterCustomer